### ISSUE TITLE
Question: Cluster with multiple virtual servers

### ISSUE THREAD

**Issue by hankilan** [DevYukine/Kurasuta#399] opened 2021-02-06 16:04 UTC
Can it be clustered with this module for Discord Client with multiple virtual servers? If not, can you give an example of how I can do it?

**Comment by DevYukine** [comment] 2021-02-08 01:28
duplicate of https://github.com/DevYukine/Kurasuta/issues/204

**Closed by DevYukine** 2021-02-08 01:28 UTC
